services: # docker-compose.yml
  # CONTAINER DB
  db:
    image: mysql:8.0
    restart: always
    # Credenziali in .env (vedi .env.example)
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      # Script di init
      - ./services/database/configs:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  # CONTAINER BE (PHP + Apache)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.be
    env_file:
      - .env
    ports: # PC-HOST:8000 ---> CONTAINER:80
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  # CONTAINER FE (Apache)
  frontend:
    image: httpd:alpine
    ports: # localhost:8080 ---> CONTAINER:80
      - "8080:80"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/
      
volumes:
    db_data:
